#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

# Each entry: MACRO_NAME followed by the headers whose contents define that font.
FONT_IDS=(
  "TIMES_8_FONT_ID times_8_regular times_8_bold times_8_bolditalic times_8_italic"
  "TIMES_9_FONT_ID times_9_regular times_9_bold times_9_bolditalic times_9_italic"
  "TIMES_12_FONT_ID times_12_regular times_12_bold times_12_bolditalic times_12_italic"
  "TIMES_14_FONT_ID times_14_regular times_14_bold times_14_bolditalic times_14_italic"
  "TIMES_16_FONT_ID times_16_regular times_16_bold times_16_bolditalic times_16_italic"
  "HELVETICA_8_FONT_ID helvetica_8_regular helvetica_8_bold helvetica_8_bolditalic helvetica_8_italic"
  "HELVETICA_9_FONT_ID helvetica_9_regular helvetica_9_bold helvetica_9_bolditalic helvetica_9_italic"
  "HELVETICA_12_FONT_ID helvetica_12_regular helvetica_12_bold helvetica_12_bolditalic helvetica_12_italic"
  "HELVETICA_14_FONT_ID helvetica_14_regular helvetica_14_bold helvetica_14_bolditalic helvetica_14_italic"
  "HELVETICA_16_FONT_ID helvetica_16_regular helvetica_16_bold helvetica_16_bolditalic helvetica_16_italic"
  "UI_10_FONT_ID helveticaui_9_regular helveticaui_9_bold"
  "UI_12_FONT_ID helveticaui_12_regular helveticaui_12_bold"
  "SMALL_FONT_ID helveticaui_8_regular"
)

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

for entry in "${FONT_IDS[@]}"; do
  read -r name headers <<< "$entry"
  echo "#define ${name} ($(
    ruby -rdigest -e 'puts ARGV.map{|f| Digest::SHA256.hexdigest(File.read("./#{f}.h")).to_i(16) }.sum % (2 ** 32) - (2 ** 31)' $headers
  ))"
done

echo ""
echo "// Font ID 0 is reserved as the \"not found\" sentinel."
echo "// Guard against any hash accidentally producing 0."
for entry in "${FONT_IDS[@]}"; do
  read -r name _ <<< "$entry"
  echo "static_assert(${name} != 0, \"Font ID collision with sentinel\");"
done
