#!/usr/bin/env python3
"""Generate Tinta's FSRS defaults and reference vectors from the pinned py-fsrs.

    python3 tools/gen-fsrs-vectors.py

Installs the pinned reference (FSRS_VERSION) into build/fsrs-venv if needed,
re-runs itself there, and writes two committed files:

  src/core/srs/FsrsDefaults.h      default weights and the version string
  test/tinta/fixtures/fsrs/vectors.txt   review sequences with the reference's
                                   stability, difficulty and interval after
                                   every step, checked by fsrs_test

The reference runs with learning and relearning steps disabled and fuzzing off,
so it behaves as pure day-based FSRS: the memory model Tinta ports. Tinta does
its own session-relative learning steps (PLAN.md section 8.1). Output is
deterministic: the same version and seed give byte-identical files.
"""

import os
import random
import subprocess
import sys
from datetime import datetime, timedelta, timezone

FSRS_VERSION = "6.3.2"
SEED = 20261003
SEQUENCES = 300

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENV = os.path.join(ROOT, "build", "fsrs-venv")
DEFAULTS_H = os.path.join(ROOT, "src", "core", "srs", "FsrsDefaults.h")
VECTORS = os.path.join(ROOT, "..", "..", "test", "tinta", "fixtures", "fsrs", "vectors.txt")


def venv_python():
    return os.path.join(VENV, "bin", "python3")


def ensure_reference():
    """Returns the fsrs module, re-executing under the venv when needed."""
    try:
        import fsrs  # noqa: F401
        from importlib.metadata import version

        if version("fsrs") == FSRS_VERSION:
            return fsrs
    except ImportError:
        pass
    if os.environ.get("TINTA_FSRS_VENV") == "1":
        sys.exit(f"fsrs=={FSRS_VERSION} is not importable inside {VENV}")
    if not os.path.exists(venv_python()):
        subprocess.check_call([sys.executable, "-m", "venv", VENV])
    subprocess.check_call(
        [venv_python(), "-m", "pip", "install", "--quiet", f"fsrs=={FSRS_VERSION}"]
    )
    env = dict(os.environ, TINTA_FSRS_VENV="1")
    os.execve(venv_python(), [venv_python(), os.path.abspath(__file__)] + sys.argv[1:], env)


def write_defaults(fsrs):
    from fsrs.scheduler import DEFAULT_PARAMETERS

    weights = ",\n".join(f"    {repr(float(w))}f" for w in DEFAULT_PARAMETERS)
    text = f"""// Generated by tools/gen-fsrs-vectors.py from py-fsrs {FSRS_VERSION}. Do not edit.
#pragma once

namespace tinta::core {{

inline constexpr char kFsrsVersion[] = "py-fsrs {FSRS_VERSION}";
inline constexpr int kFsrsWeightCount = {len(DEFAULT_PARAMETERS)};
inline constexpr float kFsrsDefaultWeights[kFsrsWeightCount] = {{
{weights},
}};

}}  // namespace tinta::core
"""
    with open(DEFAULTS_H, "w") as f:
        f.write(text)


def pick_grade(rng, style):
    if style == "easy":
        return 4
    if style == "again":
        return 1
    if style == "hard":
        return 2
    return rng.choices([1, 2, 3, 4], weights=[15, 15, 55, 15])[0]


def pick_elapsed(rng, interval):
    mode = rng.random()
    if mode < 0.50:
        return interval
    if mode < 0.62:
        return rng.randint(1, max(1, interval - 1))
    if mode < 0.77:
        return max(1, round(interval * rng.uniform(1.1, 3.0)))
    if mode < 0.90:
        return 0
    return rng.randint(30, 400)


def write_vectors(fsrs):
    from fsrs import Card, Rating, Scheduler

    rng = random.Random(SEED)
    retentions = [0.9, 0.9, 0.9, 0.8, 0.85, 0.95, 0.7, 0.97]
    max_intervals = [365, 365, 36500, 30, 3650]
    styles = ["mixed"] * 12 + ["easy", "again", "hard"]
    start = datetime(2024, 1, 1, tzinfo=timezone.utc)

    lines = [
        f"# Generated by tools/gen-fsrs-vectors.py from py-fsrs {FSRS_VERSION}"
        f" (seed {SEED}). Do not edit.",
        "# Learning/relearning steps disabled, fuzzing off, default weights.",
        "# seq <desired_retention> <maximum_interval> <steps>",
        "# <elapsed_days> <grade> <retrievability_before> <stability> <difficulty>"
        " <interval> <interval_unrounded>",
    ]
    for n in range(SEQUENCES):
        retention = retentions[n % len(retentions)] if n >= 8 else 0.9
        max_interval = rng.choice(max_intervals)
        style = rng.choice(styles)
        steps = rng.randint(4, 25)
        scheduler = Scheduler(
            desired_retention=retention,
            learning_steps=(),
            relearning_steps=(),
            maximum_interval=max_interval,
            enable_fuzzing=False,
        )
        card = Card(card_id=n + 1, due=start)
        when = start
        interval = 0
        lines.append(f"seq {retention!r} {max_interval} {steps}")
        for step in range(steps):
            # The first sequences pin each grade's initial state on its own.
            grade = (n % 4) + 1 if n < 8 and step == 0 else pick_grade(rng, style)
            elapsed = 0 if step == 0 else pick_elapsed(rng, interval)
            when = when + timedelta(days=elapsed)
            r_before = scheduler.get_card_retrievability(card, current_datetime=when)
            card, _ = scheduler.review_card(card, Rating(grade), review_datetime=when)
            interval = (card.due - when).days
            raw = (card.stability / scheduler._FACTOR) * (
                retention ** (1 / scheduler._DECAY) - 1
            )
            lines.append(
                f"{elapsed} {grade} {r_before!r} {card.stability!r}"
                f" {card.difficulty!r} {interval} {raw!r}"
            )
    os.makedirs(os.path.dirname(VECTORS), exist_ok=True)
    with open(VECTORS, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    fsrs = ensure_reference()
    write_defaults(fsrs)
    write_vectors(fsrs)
    print(f"py-fsrs {FSRS_VERSION}: wrote {os.path.relpath(DEFAULTS_H, ROOT)}"
          f" and {os.path.relpath(VECTORS, ROOT)}")


if __name__ == "__main__":
    main()
