// modules: srs
//
// Checks the FSRS port against test/fixtures/fsrs/vectors.txt, generated by
// tools/gen-fsrs-vectors.py from the pinned py-fsrs. Each sequence is run
// twice: chained (the port's own state carried from step to step, as on the
// device) and stepwise (the reference state fed in before each step).
//
// Tolerances: the reference computes in double, the port in float.
//   stability   relative 5e-5 chained, 2e-5 stepwise
//   difficulty  absolute 1e-4 chained, 2e-5 stepwise
//   retrievability absolute 5e-6
//   interval    exact, except ±1 day where the reference's unrounded interval
//               lies within the stability tolerance of a .5 tie

#include "core/srs/Fsrs.h"

#include <cmath>
#include <cstdio>

#include "check.h"

using tinta::core::Fsrs;
using tinta::core::Grade;

namespace {

constexpr double kStabilityRelChained = 5e-5;
constexpr double kStabilityRelStep = 2e-5;
constexpr double kDifficultyAbsChained = 1e-4;
constexpr double kDifficultyAbsStep = 2e-5;
constexpr double kRetrievabilityAbs = 5e-6;

struct Step {
  unsigned elapsed;
  int grade;
  double rBefore, stability, difficulty;
  int interval;
  double rawInterval;
};

double worstS = 0, worstD = 0, worstR = 0;

bool intervalMatches(int port, const Step& ref) {
  if (port == ref.interval) return true;
  const double frac = ref.rawInterval - std::floor(ref.rawInterval);
  const double nearTie = std::fabs(frac - 0.5) <= ref.rawInterval * kStabilityRelChained;
  return nearTie && (port == ref.interval + 1 || port == ref.interval - 1);
}

void checkStep(const Fsrs& fsrs, const Fsrs::Memory& got, float rBefore, const Step& ref, bool chained, int seq,
               int step) {
  const double relS = std::fabs(got.stability - ref.stability) / ref.stability;
  const double absD = std::fabs(got.difficulty - ref.difficulty);
  const double absR = std::fabs(rBefore - ref.rBefore);
  if (chained) {
    if (relS > worstS) worstS = relS;
    if (absD > worstD) worstD = absD;
    if (absR > worstR) worstR = absR;
  }
  const double tolS = chained ? kStabilityRelChained : kStabilityRelStep;
  const double tolD = chained ? kDifficultyAbsChained : kDifficultyAbsStep;
  const int interval = fsrs.interval(got.stability);
  const bool ok = relS <= tolS && absD <= tolD && absR <= kRetrievabilityAbs && intervalMatches(interval, ref);
  if (!ok) {
    std::printf("  seq %d step %d (%s): S %.9g/%.9g D %.9g/%.9g R %.9g/%.9g ivl %d/%d\n", seq, step,
                chained ? "chained" : "stepwise", got.stability, ref.stability, got.difficulty, ref.difficulty, rBefore,
                ref.rBefore, interval, ref.interval);
    ++tinta_test::failures();
  }
}

}  // namespace

int main() {
  std::FILE* f = std::fopen("fixtures/fsrs/vectors.txt", "r");
  CHECK(f != nullptr);
  if (!f) return tinta_test::result();

  char line[256];
  int sequences = 0, steps = 0;
  Step seq[64];
  double retention = 0;
  int maxInterval = 0, count = 0;

  auto runSequence = [&]() {
    Fsrs fsrs(static_cast<float>(retention), static_cast<uint16_t>(maxInterval));
    Fsrs::Memory chained{0, 0}, stepwise{0, 0};
    for (int i = 0; i < count; ++i) {
      const Step& ref = seq[i];
      const Grade grade = static_cast<Grade>(ref.grade);
      float rChained = 0, rStep = 0;
      if (i == 0) {
        chained = fsrs.initial(grade);
        stepwise = chained;
      } else {
        rChained = fsrs.retrievability(chained.stability, ref.elapsed);
        chained = fsrs.next(chained, ref.elapsed, grade);
        const Fsrs::Memory prev{static_cast<float>(seq[i - 1].stability), static_cast<float>(seq[i - 1].difficulty)};
        rStep = fsrs.retrievability(prev.stability, ref.elapsed);
        stepwise = fsrs.next(prev, ref.elapsed, grade);
      }
      checkStep(fsrs, chained, rChained, ref, true, sequences, i);
      checkStep(fsrs, stepwise, rStep, ref, false, sequences, i);
      ++steps;
    }
    ++sequences;
  };

  while (std::fgets(line, sizeof line, f)) {
    if (line[0] == '#') continue;
    if (line[0] == 's') {
      if (count > 0) runSequence();
      int n = 0;
      CHECK(std::sscanf(line, "seq %lf %d %d", &retention, &maxInterval, &n) == 3);
      CHECK(n > 0 && n <= 64);
      count = 0;
      continue;
    }
    Step s;
    if (std::sscanf(line, "%u %d %lf %lf %lf %d %lf", &s.elapsed, &s.grade, &s.rBefore, &s.stability, &s.difficulty,
                    &s.interval, &s.rawInterval) == 7 &&
        count < 64) {
      seq[count++] = s;
    }
  }
  if (count > 0) runSequence();
  std::fclose(f);

  CHECK_EQ(sequences, 300);
  CHECK(steps > 3000);
  std::printf(
      "  %d sequences, %d steps against %s; worst chained: S rel %.2g, D abs %.2g, "
      "R abs %.2g\n",
      sequences, steps, tinta::core::kFsrsVersion, worstS, worstD, worstR);

  // Spot checks that do not depend on the fixture.
  Fsrs fsrs;
  CHECK_NEAR(fsrs.initial(Grade::Good).stability, 2.3065, 1e-6);
  CHECK_NEAR(fsrs.retrievability(10.0f, 10), 0.9, 1e-5);
  CHECK_EQ(fsrs.interval(0.2f), 1);
  CHECK_EQ(fsrs.interval(5000.0f), 365);
  fsrs.configure(0.9f, 36500);
  CHECK_EQ(fsrs.interval(5000.0f), 5000);
  CHECK_EQ(fsrs.interval(1e9f), 36500);

  return tinta_test::result();
}
