#!/bin/sh
# Regenerate the committed Tinta test fixtures from lib/Tinta/tools:
#
#   sh test/tinta/make-fixtures.sh          # mini.pack, mini.expect.txt, fold_vectors.txt,
#                                           # sim-fixture.pack, charset_expected.h
#   sh test/tinta/make-fixtures.sh --full   # also fixtures/full.pack (the whole course, not committed)
#
# Run it after a change to tools/packc, tools/charset.py or a fixture course
# (fixtures/content-mini, fixtures/content-sim), and commit what changes.
# Packs carry their build time: set SOURCE_DATE_EPOCH to reproduce one exactly.
# fixtures/fsrs/vectors.txt comes from lib/Tinta/tools/gen-fsrs-vectors.py.

set -e

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
TOOLS="$ROOT/lib/Tinta/tools"
FIX="$ROOT/test/tinta/fixtures"
SCRATCH="$ROOT/test/tinta/build/fixtures"
rm -rf "$SCRATCH"
mkdir -p "$SCRATCH"

# content-mini compiles in place: new item ids are appended to its ids.lock.
python3 "$TOOLS/packc" --content "$FIX/content-mini" --out "$FIX/mini.pack" --quiet
python3 "$TOOLS/packc/tests/pack_expect.py" "$FIX/mini.pack" >"$FIX/mini.expect.txt"
python3 "$TOOLS/packc/fold.py" --vectors >"$FIX/fold_vectors.txt"

# content-sim is frozen, so it compiles from a scratch copy and its ids.lock is never written.
cp -R "$FIX/content-sim" "$SCRATCH/content-sim"
python3 "$TOOLS/packc" --content "$SCRATCH/content-sim" --out "$FIX/sim-fixture.pack" --quiet 2>/dev/null

python3 - "$TOOLS" >"$FIX/charset_expected.h" <<'EOF'
import sys
sys.path.insert(0, sys.argv[1])
import charset


def c_string(text):
    return '"' + "".join(f"\\x{b:02x}" for b in text.encode("utf-8")) + '"'


print("// Generated by test/tinta/make-fixtures.sh from lib/Tinta/tools/charset.py.")
print("#pragma once")
print("#include <cstdint>")
print()
print(f"constexpr uint32_t kExpectedFirst = 0x{charset.FIRST:X};")
print(f"constexpr uint32_t kExpectedLast = 0x{charset.LAST:X};")
print("// slot -> source codepoint (0 = empty), for every slot FIRST..LAST")
print("constexpr uint32_t kExpectedSlotSource[] = {")
for slot, source in charset.slots():
    print(f"    0x{source or 0:04X},  // 0x{slot:02X}")
print("};")
print("// every supported codepoint below U+10000 -> slot (-1 = drawn without a slot)")
print("struct ExpectedSlot { uint32_t cp; int32_t slot; };")
print("constexpr ExpectedSlot kExpectedSupported[] = {")
for cp in range(0x10000):
    if charset.is_supported(cp):
        slot = charset.REMAP.get(cp, -1 if cp in charset.PASSTHROUGH else cp)
        print(f"    {{0x{cp:04X}, {slot}}},")
print("};")
print("struct ExpectedEncoding { const char* in; const char* out; };  // out nullptr = rejected")
print("constexpr ExpectedEncoding kExpectedEncodings[] = {")
samples = [
    "¿Él está en Ávila? —Sí.",
    "“Hola”, dijo ‘ella’ • 5 € – 3",
    "línea\nnueva…",
    "pingüino, niño, ¡ay!",
    "日本",
    "tab\there",
    "emoji 🙂",
    "",
]
for text in samples:
    try:
        out = c_string(charset.encode(text))
    except charset.CharsetError:
        out = "nullptr"
    print(f"    {{{c_string(text)}, {out}}},")
print("};")
EOF

if [ "$1" = "--full" ]; then
  # From a scratch copy, so lib/Tinta/content/ids.lock is never written.
  cp -R "$ROOT/lib/Tinta/content" "$SCRATCH/content-full"
  python3 "$TOOLS/packc" --content "$SCRATCH/content-full" --out "$FIX/full.pack" --allow-missing-examples --quiet 2>/dev/null
fi

echo "fixtures regenerated in $FIX"
