"""Item generation, stable ids (content/ids.lock, PLAN.md 7.6) and distractor candidates."""

from __future__ import annotations

import os
import re
import zlib
from dataclasses import dataclass, field

from . import forms as F
from .build import WORD_RE
from .diag import Where
from .fold import fold
from .sources import POS

NONE16 = 0xFFFF
VOCAB_RECOGNISE, VOCAB_PRODUCE, CLOZE, CONJUGATION, GENDER, PHRASE, WORD_ORDER = range(7)
KIND_NAMES = ("recognise", "produce", "cloze", "conjugation", "gender", "phrase", "order")
IF_FREQUENCY, IF_PHRASEBOOK = 4, 8
MAX_CANDIDATES = 8
OPTION_MAX = 28  # characters in one answer cell; longer candidates are skipped
WORD_ORDER_TOKENS = (3, 8)

# Distractors come from lemmas of the same group (PLAN.md 4.3: same part of speech).
POS_GROUP = {POS["noun"]: 1, POS["verb"]: 2, POS["adj"]: 3, POS["adv"]: 4, POS["expr"]: 5,
             POS["interj"]: 5, POS["pron"]: 6, POS["det"]: 6, POS["prep"]: 6, POS["conj"]: 6,
             POS["num"]: 7, POS["propn"]: 0}

# The progress store marks damaged records with 0xFFFFFFFF; uids start at 1.
RESERVED_UID = 0xFFFFFFFF

LOCK_HEADER = (
    "# Tinta stable item ids (PLAN.md 7.6). Generated by tools/packc; commit it.\n"
    "# Append-only: never edit, reorder or delete a line. uid<TAB>key<TAB>check\n"
)


@dataclass
class Item:
    key: str
    kind: int
    lesson: int
    a: int
    b: int
    where: Where
    flags: int = 0
    prereq: int = NONE16
    candidates: list = field(default_factory=list)   # lemma ids, strings or sentence ids
    must_show: int = 0
    closed: bool = False   # a cloze on a closed-class word: one or two distractors suffice
    uid: int = 0
    index: int = 0


def _check(uid: int, key: str) -> str:
    line = str(uid) + "\t" + key
    return f"{zlib.crc32(line.encode()):08x}"


class IdLock:
    def __init__(self, path: str, diag):
        self.path = path
        self.by_key: dict[str, int] = {}
        self.next_uid = 1
        self.appended: list[tuple[int, str]] = []
        if not os.path.exists(path):
            return
        with open(path, encoding="utf-8") as fh:
            for lineno, raw in enumerate(fh, 1):
                line = raw.rstrip("\n")
                if not line or line.startswith("#"):
                    continue
                where = Where(path, lineno)
                parts = line.split("\t")
                if len(parts) != 3 or not parts[0].isdigit():
                    diag.error(where, "ids", "malformed ids.lock line (uid<TAB>key<TAB>check)")
                    continue
                uid, key, check = int(parts[0]), parts[1], parts[2]
                if uid != self.next_uid:
                    diag.error(where, "ids", f"uid {uid} out of sequence (expected {self.next_uid}): "
                               "lines of ids.lock must never be deleted or reordered")
                if check != _check(uid, key):
                    diag.error(where, "ids", f"checksum mismatch for uid {uid}: the line was edited; "
                               "ids never change meaning (restore it and append a new id instead)")
                if key in self.by_key:
                    diag.error(where, "ids", f"key '{key}' appears twice in ids.lock")
                self.by_key[key] = uid
                self.next_uid = max(self.next_uid, uid) + 1

    def uid_for(self, key: str) -> int:
        if key not in self.by_key:
            if self.next_uid >= RESERVED_UID:
                raise ValueError("ids.lock is full: uid 0xFFFFFFFF is reserved")
            self.by_key[key] = self.next_uid
            self.appended.append((self.next_uid, key))
            self.next_uid += 1
        return self.by_key[key]

    def write(self) -> None:
        if not self.appended and not os.path.exists(self.path):
            return
        exists = os.path.exists(self.path)
        with open(self.path, "a", encoding="utf-8") as fh:
            if not exists:
                fh.write(LOCK_HEADER)
            for uid, key in self.appended:
                fh.write(f"{uid}\t{key}\t{_check(uid, key)}\n")
            # Publish a pack only after its item identities have reached storage.
            fh.flush()
            os.fsync(fh.fileno())
        self.appended = []


def generate(b) -> None:
    from .build import SF_WORD_ORDER, TF_TARGET  # noqa: PLC0415

    d = b.diag
    out: list[Item] = []
    recognise: dict[int, int] = {}   # lemma id -> index into out

    def add(item: Item) -> Item:
        item.index = len(out)
        out.append(item)
        return item

    def vocab(lemma, lesson: int, flags: int, where: Where) -> None:
        recognise[lemma.id] = add(Item(f"vocab:{lemma.key}:recognise", VOCAB_RECOGNISE, lesson, lemma.id, 0,
                                       where, flags)).index

    def sentence_items(sent, lesson: int, flags: int, cloze: bool) -> list[Item]:
        """Cloze items for a sentence's targets, or its word-order item."""
        made = []
        if cloze:
            for t_index, tok in enumerate(sent.tokens):
                if not tok.flags & TF_TARGET or tok.lemma is None:
                    continue
                if tok.tag & F.ENCLITIC:
                    d.error(sent.src.where, "cloze",
                            f"target '{tok.surface}' has attached pronouns; mark the verb in another sentence")
                    continue
                made.append(Item(_cloze_key(sent, t_index), CLOZE, lesson, sent.id, t_index, sent.src.where,
                                 flags, prereq=recognise.get(tok.lemma.id, NONE16)))
        elif sent.flags & SF_WORD_ORDER:
            lo, hi = WORD_ORDER_TOKENS
            if lo <= len(sent.tokens) <= hi:
                made.append(Item(f"order:{sentence_key(sent)}", WORD_ORDER, lesson, sent.id, 0, sent.src.where, flags))
            else:
                d.error(sent.src.where, "order", f"word-order sentence has {len(sent.tokens)} words; use {lo} to {hi}")
        return made

    def follow_ups(lemma, lesson: int, flags: int, where: Where) -> None:
        rec = recognise[lemma.id]
        if lemma.pos == POS["noun"] and lemma.gender in (1, 2) and not lemma.plural_only:
            add(Item(f"gender:{lemma.key}", GENDER, lesson, lemma.id, 0, where, flags, prereq=rec))
        add(Item(f"vocab:{lemma.key}:produce", VOCAB_PRODUCE, lesson, lemma.id, 0, where, flags, prereq=rec))

    for lesson in b.lessons:
        lesson.first_item = len(out)
        where = lesson.src.where
        for lemma in lesson.new:
            vocab(lemma, lesson.id, 0, where)
        for lemma in lesson.new:
            follow_ups(lemma, lesson.id, 0, where)
        for spec, swhere in lesson.src.conjugate:
            for lemma, tag in _conjugation_specs(b, spec, swhere):
                add(Item(f"conj:{lemma.key}:{F.tag_name(tag)}", CONJUGATION, lesson.id, lemma.id, tag, swhere,
                         prereq=recognise.get(lemma.id, NONE16)))
        for sid in lesson.sentences:
            for item in sentence_items(b.sentences[sid], lesson.id, 0, cloze=True):
                add(item)
        for sid in lesson.sentences:
            for item in sentence_items(b.sentences[sid], lesson.id, 0, cloze=False):
                add(item)
        lesson.item_count = len(out) - lesson.first_item

    deck = [lem for lem in b.lemmas if lem.flags & 16 and lem.lesson == NONE16]
    deck.sort(key=lambda lem: (lem.entry.freq or 1 << 30, lem.id))
    for lemma in deck:
        vocab(lemma, NONE16, IF_FREQUENCY, lemma.entry.where)
    for lemma in deck:
        follow_ups(lemma, NONE16, IF_FREQUENCY, lemma.entry.where)
    # Deck sentences (content/deck/*.yaml): cloze and word-order items after the deck's
    # vocabulary, in the frequency order of the words they practise.
    def rank(sent) -> tuple:
        targets = [t.lemma for t in sent.tokens if t.flags & TF_TARGET and t.lemma is not None]
        return min([(lem.entry.freq or 1 << 30) for lem in targets] or [1 << 30]), sent.id
    deck_sentences = sorted((b.sentences[sid] for f in b.deck_files for sid in f["sentences"]), key=rank)
    for sent in deck_sentences:
        for item in sentence_items(sent, NONE16, IF_FREQUENCY, cloze=True):
            add(item)
    for sent in deck_sentences:
        for item in sentence_items(sent, NONE16, IF_FREQUENCY, cloze=False):
            add(item)

    for p_index, entry in enumerate(b.phrase_entries):
        sent = b.sentences[entry.sentence]
        add(Item(f"phrase:{sentence_key(sent)}", PHRASE, NONE16, entry.sentence, p_index, sent.src.where, IF_PHRASEBOOK))

    sentence_ids: dict[str, object] = {}
    for sent in b.sentences:
        if sent.src.id:
            if sent.src.id in sentence_ids:
                d.error(sent.src.where, "duplicate", f"sentence id '{sent.src.id}' is also used at "
                        f"{sentence_ids[sent.src.id]}")
            sentence_ids[sent.src.id] = sent.src.where
    keys: dict[str, Item] = {}
    for item in out:
        if item.key in keys:
            d.error(item.where, "duplicate", f"item '{item.key}' generated twice (also {keys[item.key].where}): "
                    "the same sentence is used twice; reword one or give it an id:")
        keys[item.key] = item
        if item.prereq != NONE16 and item.prereq >= item.index:
            item.prereq = NONE16  # never gate on something taught later
    for item in out:
        if item.kind in (VOCAB_RECOGNISE, VOCAB_PRODUCE):
            b.lemmas[item.a].flags |= 8  # HAS_ITEMS

    lock = IdLock(b.course.ids_path, d)
    for item in out:
        try:
            item.uid = lock.uid_for(item.key)
        except ValueError as exc:
            d.error(item.where, "ids", str(exc))
    b.new_uids = len(lock.appended)
    b.retired_uids = len(set(lock.by_key) - set(keys))
    b.id_lock = lock
    b.items = out
    _candidates(b)


def sentence_key(sent) -> str:
    """What an item key says about its sentence. Keys never depend on position, so
    inserting or reordering sentences keeps every uid (PLAN.md 7.6); rewording a
    sentence without an `id:` retires its items and makes new ones."""
    return f"id:{sent.src.id}" if sent.src.id else fold(sent.es)


def _cloze_key(sent, t_index: int) -> str:
    target = fold(sent.tokens[t_index].surface)
    same = [i for i, t in enumerate(sent.tokens[:t_index]) if t.flags & 1 and fold(t.surface) == target]
    suffix = f":{len(same) + 1}" if same else ""
    return f"cloze:{sentence_key(sent)}:{target}{suffix}"


def _conjugation_specs(b, spec: str, where: Where):
    d = b.diag
    key, colon, form = spec.partition(":")
    lemma = b.by_key.get(key.strip())
    if lemma is None or lemma.verb is None:
        d.error(where, "link", f"conjugate '{spec}': '{key}' is not a verb in the lexicon")
        return []
    form = form.strip()
    if not colon or not form:
        d.error(where, "schema", f"conjugate '{spec}': write verb:tense or verb:tense.person")
        return []
    if "." in form:
        try:
            return [(lemma, F.parse_tag(form))]
        except F.TagError as exc:
            d.error(where, "peninsular" if "vosotros" in str(exc) else "schema", f"conjugate '{spec}': {exc}")
            return []
    if form not in F.TENSES:
        d.error(where, "schema", f"conjugate '{spec}': unknown tense '{form}' ({', '.join(F.TENSES)})")
        return []
    persons = F.IMPERATIVE_PERSONS if form in ("imp", "impneg") else F.PERSONS
    return [(lemma, F.verb_tag(form, p)) for p in persons]


# --- distractor candidates -------------------------------------------------------

def _gap_text(text: str, model: str) -> str:
    """An option as it would stand in the gap: no ¿?¡! of a headword, capitalised like the answer."""
    words = WORD_RE.findall(text)
    if words:
        text = text[text.index(words[0]):text.rindex(words[-1]) + len(words[-1])]
    return text[:1].upper() + text[1:] if model[:1].isupper() else text


def _confusable_partners(b, lemma) -> list:
    out = []
    for conf in b.confusables:
        if lemma in conf["members"]:
            out += [m for m in conf["members"] if m is not lemma and m not in out]
    return out


_POOLS: dict = {}
_POSITIONS: dict = {}
_HEAD = 64  # candidates whose ties are broken per item; the rest keep their pool order


def _vocab_pool(b, lemma, produce: bool, uid: int = 0) -> list:
    """Distractor lemmas for `lemma`, best first. The ranking (partners, same topic, nearest
    in the course) is per lemma and cached; ties are broken per item by its uid, so items on
    similar words do not all show the same few options."""
    key = (id(b), lemma.id, produce)
    if key not in _POOLS:
        _POOLS[key] = _make_pool(b, lemma, produce)
    ranked = _POOLS[key]
    if len(ranked) > _HEAD:
        cutoff = ranked[_HEAD - 1][0]
        end = next((i for i in range(_HEAD, len(ranked)) if ranked[i][0] > cutoff), len(ranked))
    else:
        end = len(ranked)
    head = sorted(ranked[:end], key=lambda e: (e[0], zlib.crc32(f"{uid}:{e[1].key}".encode())))
    return [o for _r, o in head] + [o for _r, o in ranked[end:]]


def _position(b, lemma) -> int:
    """Where the learner meets a lemma, on one scale: lessons first (by the lesson where it is
    introduced or first used), then the frequency deck by rank, then everything else."""
    if not _POSITIONS:
        first = _first_lessons(b)
        for lem in b.lemmas:
            if lem.id in first:
                _POSITIONS[lem.id] = 10 * first[lem.id]
            elif lem.entry.freq:
                _POSITIONS[lem.id] = 100_000 + lem.entry.freq
            else:
                _POSITIONS[lem.id] = 1_000_000
    return _POSITIONS[lemma.id]


def _make_pool(b, lemma, produce: bool) -> list:
    group = POS_GROUP.get(lemma.pos, 0)
    pool = []
    for other in _course_lemmas(b, group):
        if other is lemma or not group or POS_GROUP.get(other.pos) != group or other.key in lemma.synonyms:
            continue
        if abs(other.level - lemma.level) > 1 or other.senses & lemma.senses:
            continue
        if other.reg == 3 and lemma.reg != 3:
            continue
        if produce and other.fold == lemma.fold:
            continue
        pool.append(other)
    partners = _confusable_partners(b, lemma)
    # An authored set is the point: calor / caliente are offered against each other.
    pool += [p for p in partners if p not in pool and not (produce and p.fold == lemma.fold)]

    here = _position(b, lemma)

    def rank(other):
        # Authored partners, then the same topic, then the nearest in the course: nearby
        # lessons for lesson words, nearby frequency ranks for deck words.
        return (other not in partners, other.entry.topic != lemma.entry.topic or not lemma.entry.topic,
                abs(_position(b, other) - here))
    return sorted(((rank(other), other) for other in pool), key=lambda e: e[0])


_GROUPS: dict = {}


def _course_lemmas(b, group: int) -> list:
    """Lemmas of a distractor group, dictionary-only rows excluded (they are never options)."""
    key = (id(b), group)
    if key not in _GROUPS:
        _GROUPS[key] = [lem for lem in b.lemmas if POS_GROUP.get(lem.pos) == group and not lem.flags & 64]
    return _GROUPS[key]


def _first_lessons(b) -> dict[int, int]:
    """Lemma id -> the first lesson where the learner meets it (introduced or in a sentence)."""
    first: dict[int, int] = {}
    for lemma in b.lemmas:
        if lemma.lesson != NONE16:
            first[lemma.id] = lemma.lesson
    for sent in b.sentences:
        if sent.lesson == NONE16:
            continue
        for tok in sent.tokens:
            if tok.lemma is not None and sent.lesson < first.get(tok.lemma.id, NONE16):
                first[tok.lemma.id] = sent.lesson
    return first


def _related(a, b) -> bool:
    """Two lemmas that must not appear together among options: same sense or declared synonyms."""
    return bool(a.senses & b.senses) or a.key in b.synonyms or b.key in a.synonyms


def _select(pool, met, partners, chosen: list | None = None, unrelated: bool = True) -> list:
    """Up to MAX_CANDIDATES (lemma, text) options, pairwise distinct as shown and unrelated in
    meaning, so any three the device picks are three different answers. Words the learner has
    met come first; others only to reach three. Authored partners always qualify. `chosen`
    seeds the result (options already taken)."""
    chosen = list(chosen or [])

    def fits(other, text) -> bool:
        return all(text.lower() != t.lower() and not (unrelated and _related(other, c)) for c, t in chosen)

    for other, text in pool:
        if (other in partners or met(other)) and fits(other, text):
            chosen.append((other, text))
            if len(chosen) == MAX_CANDIDATES:
                return chosen
    for other, text in pool:
        if len(chosen) >= 3:
            break
        if all(other is not c for c, _t in chosen) and fits(other, text):
            chosen.append((other, text))
    return chosen


def _noun_option(other, gender: int, plural: bool) -> str | None:
    """`other` in the gender and number the sentence shows for the target noun, or None."""
    if other.pos != POS["noun"]:
        return None
    if other.gender == 3:  # amigo/amiga, estudiante
        fem = gender == 2 and bool(other.feminine)
        if plural:
            return other.form_for(F.NOMINAL["fpl"] if fem else F.NOMINAL["mpl"]) or other.form_for(F.NOMINAL["pl"])
        return other.feminine if fem else other.es
    if other.gender != gender:
        return None
    if other.plural_only:
        return other.es if plural else None
    return other.form_for(F.NOMINAL["pl"]) if plural else other.es


def _adjective_option(other, tag: int) -> str | None:
    if other.pos != POS["adj"]:
        return None
    fem = tag in (F.NOMINAL["f"], F.NOMINAL["fpl"])
    plural = tag in (F.NOMINAL["pl"], F.NOMINAL["mpl"], F.NOMINAL["fpl"])
    if fem and other.feminine:
        return other.form_for(F.NOMINAL["fpl"]) if plural else other.feminine
    if plural:
        return other.form_for(F.NOMINAL["mpl"]) or other.form_for(F.NOMINAL["pl"])
    return other.es


# Masculine singular articles, which also go before feminine nouns with a stressed
# a/ha (el agua, un hacha).
EL_ARTICLES = frozenset({"el", "un", "al", "del"})
LA_ARTICLES = frozenset({"la", "una"})  # never before agua: la agua and una agua give themselves away


def _option_for(lemma, tag: int, other, el_context: bool = False, after_la: bool = False) -> str | None:
    """`other` inflected to agree like the target (lemma, tag) does, so agreement alone never
    rules an option out: una [casa] offers feminine nouns, [chidas] feminine plurals, and
    el [agua] or el [camión] nouns that can follow el (masculine, or like agua)."""
    if lemma.pos == POS["noun"] and el_context:
        if other.pos != POS["noun"] or other.plural_only:
            return None
        if other.gender in (1, 3) or other.flags & 4:  # LF_EL_FEMININE
            return other.es
        return None
    if lemma.pos == POS["noun"] and after_la and other.flags & 4:
        return None
    if lemma.pos == POS["noun"]:
        if tag in (F.NOMINAL["f"], F.NOMINAL["fpl"]):
            gender = 2
        elif tag in (F.NOMINAL["m"], F.NOMINAL["mpl"]) or lemma.gender == 3:
            gender = 1
        else:
            gender = lemma.gender
        plural = lemma.plural_only or tag in (F.NOMINAL["pl"], F.NOMINAL["mpl"], F.NOMINAL["fpl"])
        return _noun_option(other, gender, plural)
    if lemma.pos == POS["adj"]:
        return _adjective_option(other, tag)
    return other.form_for(tag)


def _gender_shown(tok) -> int:
    """1 or 2 when a noun, determiner or pronoun token shows its gender, else 0."""
    lem = tok.lemma
    if lem is None or lem.pos not in (POS["noun"], POS["det"], POS["pron"]):
        return 0
    if tok.tag in (F.NOMINAL["f"], F.NOMINAL["fpl"]):
        return 2
    if tok.tag in (F.NOMINAL["m"], F.NOMINAL["mpl"]) or (lem.pos == POS["noun"] and lem.gender == 3):
        return 1
    return lem.gender if lem.gender in (1, 2) else 0  # mi, me, se show none


COPULAS = frozenset({"ser", "estar", "parecer"})


def _controller_gender(sent, t_index: int) -> int:
    """Gender of what an adjective agrees with: the nearest gendered word before it
    (mi hermana mayor), or after ser/estar the clause's subject, not an object or
    measure in between (Mi abuelo tiene noventa años y está muy joven: abuelo)."""
    toks = sent.tokens
    start = 0
    for j in range(1, t_index + 1):
        if any(ch in ".?!" for ch in sent.es[toks[j - 1].end:toks[j].start]):
            start = j  # a new sentence inside the item
    clause = toks[start:t_index]
    if any(t.lemma is not None and t.lemma.key in COPULAS and F.is_verb_tag(t.tag) for t in clause):
        for t in clause + toks[t_index + 1:]:  # ¿Está muy sano tu abuelo? looks after the target too
            if _gender_shown(t):
                return _gender_shown(t)
        return 0
    for t in reversed(clause):
        if _gender_shown(t):
            return _gender_shown(t)
    return 0


def _agreement_tag(sent, t_index: int, tok) -> int:
    """The form an adjective's options should take. A form that shows gender and number
    (sano, sanas) is copied as it is; an adjective with one form for both genders (mayor,
    joven) takes its gender from what it describes and keeps its own number."""
    if tok.lemma.feminine or tok.tag not in (F.BASE, F.NOMINAL["pl"]):
        return tok.tag
    plural = tok.tag == F.NOMINAL["pl"]
    if _controller_gender(sent, t_index) == 2:
        return F.NOMINAL["fpl" if plural else "f"]
    return F.NOMINAL["mpl"] if plural else F.BASE


# The unit from which lessons have taught each tense (the course teaches no future,
# conditional or non-command subjunctive as grammar). Items outside lessons come after all.
TAUGHT_FROM_UNIT = {"pres": 0, "imp": 5, "impneg": 5, "pret": 9, "impf": 10}


def _taught_tenses(b, lesson: int) -> frozenset:
    unit = b.course.units[b.lessons[lesson].unit].number if lesson != NONE16 else 1 << 16
    return frozenset(t for t, first in TAUGHT_FROM_UNIT.items() if unit >= first)


def _verb_candidates(lemma, tag: int, answer: str, bare: bool, skip_forms: frozenset = frozenset(),
                     tenses: frozenset | None = None) -> list[str]:
    """Other forms of the verb, nearest cells first. `tenses` limits them to what the learner
    has been taught (plus the target's own tense): no conditional against a present request."""
    from .build import _bare  # noqa: PLC0415

    tense, person = F.verb_tag_parts(tag)
    conj = lemma.verb
    order = [(tense, p) for p in F.PERSONS if p != person]
    order += [(t, person) for t in ("pres", "pret", "impf", "fut", "subj", "cond", "imp", "impneg") if t != tense]
    order += [(t, p) for t in F.TENSES for p in F.PERSONS]
    out: list[str] = []
    for key in order:
        form = conj.forms.get(key)
        if not form or (tenses is not None and key[0] != tense and key[0] not in tenses):
            continue
        form = _bare(form) if bare else form
        if form.lower() in skip_forms:  # by spelling: mire is subj.1s and the usted command
            continue
        if form.lower() != answer.lower() and form not in out:
            out.append(form)
    return out


# Words that show which "you" a verb form addresses (PLAN.md 4.2: tú and usted).
# Address formulas count by spelling: in the course they are often lemmas of their own
# (disculpe), not commands of disculpar.
TU_MARKERS = frozenset({"tú", "te", "ti", "tu", "tus", "contigo", "disculpa", "perdona", "oye", "mira"})
USTED_MARKERS = frozenset({"usted", "su", "sus", "le", "señor", "señora", "señorita", "don", "doña",
                           "disculpe", "perdone", "oiga", "mire", "permítame"})
_YOU = re.compile(r"\byou(r|rs|rself)?\b", re.IGNORECASE)


PLURAL_MARKERS = frozenset({"ustedes", "les", "disculpen", "perdonen", "oigan", "miren"})
_CLAUSE_BREAK = re.compile(r"[.,;:!?¡¿—()\"“”]")


def _vocative(sent) -> str:
    """"sg" or "pl" when the sentence addresses someone by name or noun (Ana, ...; ..., chicos)."""
    toks = sent.tokens
    for tok, gap in ((toks[0], sent.es[toks[0].end:toks[1].start] if len(toks) > 1 else ""),
                     (toks[-1], sent.es[toks[-2].end:toks[-1].start] if len(toks) > 1 else "")):
        lem = tok.lemma
        if lem is None or lem.pos not in (POS["propn"], POS["noun"]) or "," not in gap:
            continue
        plural = lem.plural_only or tok.tag in (F.NOMINAL["pl"], F.NOMINAL["mpl"], F.NOMINAL["fpl"])
        return "pl" if plural else "sg"
    return ""


def _you_conflicts(sent, t_index: int, tok) -> frozenset:
    """Spellings of the target verb that answer the same "you" sentence another way.

    "¿De dónde [eres]?" ("Where are you from?") fits usted's "es" and ustedes'
    "son" too; "¡[Mira]!" may be a tú command, so "Mire" and "Miren" fit; "No me
    [mires]" excludes "mire" even where "mire" is also subj.1s. A reading stays
    an option only when the sentence rules it out (tú/usted/plural cues, a
    vocative).
    """
    from .build import _bare  # noqa: PLC0415

    conj = tok.lemma.verb
    tense, person = F.verb_tag_parts(tok.tag & ~F.ENCLITIC)
    readings = set()
    if tense in ("imp", "impneg") or person == "2s" or (person in ("3s", "3p") and _YOU.search(sent.en)):
        readings.add((tense, person))
    command = conj.forms.get(("imp", "2s"))
    clause_start = t_index == 0 or bool(_CLAUSE_BREAK.search(sent.es[sent.tokens[t_index - 1].end:tok.start]))
    if command and _bare(command).lower() == tok.surface.lower() and clause_start:
        readings.add(("imp", "2s"))  # Mira, ¡Saca...!: may be a tú command
    if not readings:
        return frozenset()
    words = {t.surface.lower() for t in sent.tokens if t is not tok}  # ¡[Mira]! is no cue for itself
    vocative = _vocative(sent)
    usted_command = any(t is not tok and t.lemma is not None and t.lemma.verb is not None and F.is_verb_tag(t.tag)
                        and F.verb_tag_parts(t.tag & ~F.ENCLITIC) in (("imp", "3s"), ("impneg", "3s"))
                        for t in sent.tokens)
    tu = bool(words & TU_MARKERS)
    usted = bool(words & USTED_MARKERS) or usted_command
    plural = bool(words & PLURAL_MARKERS) or vocative == "pl"
    singular = tu or usted or vocative == "sg"
    ruled_out = {"2s": usted or plural, "3s": tu or plural, "3p": singular}
    excluded = set()
    for cell_tense, cell_person in readings:
        for other in ("2s", "3s", "3p"):
            if other != cell_person and not ruled_out[other]:
                form = conj.forms.get((cell_tense, other))
                if form:
                    excluded.add(_bare(form).lower())
    return frozenset(excluded)


# Kinds of function words: a cloze on one offers only others of the same kind.
FUNCTION_KINDS = {
    "article": "el la los las un una unos unas al del",
    "possessive": "mi mis tu tus su sus nuestro nuestra nuestros nuestras",
    "demonstrative": "este esta estos estas ese esa esos esas aquel aquella aquellos aquellas esto eso aquello",
    "subject": "yo tú él ella usted nosotros nosotras ellos ellas ustedes",
    "object": "me te se nos lo la los las le les",
    "prepositional": "mí ti conmigo contigo",
    "interrogative": "qué quién quiénes cuál cuáles cuánto cuánta cuántos cuántas dónde cómo cuándo",
}
_KIND_OF = {}
for _kind, _words in FUNCTION_KINDS.items():
    for _w in _words.split():
        _KIND_OF.setdefault(_w, _kind)


def function_kind(lemma) -> tuple[int, str]:
    """(part of speech, kind) of a determiner, pronoun, preposition or conjunction."""
    if lemma.pos in (POS["prep"], POS["conj"]):
        return lemma.pos, ""
    return lemma.pos, _KIND_OF.get(lemma.es.lower(), "other")


def _function_option(lemma, tag: int, other, gender: int, plural: bool) -> str | None:
    """A determiner or pronoun of the same kind, agreeing like the target."""
    if function_kind(other) != function_kind(lemma):
        return None
    if lemma.pos != POS["det"]:
        return other.form_for(tag) or (other.es if not (other.feminine or other.plural) else None)
    if other.gender in (1, 2):  # la, los: fixed gender and number
        return other.es if other.gender == gender and other.plural_only == plural else None
    if plural:
        form = other.form_for(F.NOMINAL["fpl" if gender == 2 else "mpl"]) or other.form_for(F.NOMINAL["pl"])
        return form
    return (other.feminine or other.es) if gender == 2 else other.es


def _det_agreement(sent, t_index: int, tok) -> tuple[int, bool]:
    """Gender and number a determiner target must show: from the noun after it, else its own form."""
    lemma = tok.lemma
    for nxt in sent.tokens[t_index + 1:t_index + 3]:
        if nxt.lemma is not None and nxt.lemma.pos == POS["noun"]:
            if nxt.tag in (F.NOMINAL["f"], F.NOMINAL["fpl"]):
                gender = 2
            else:
                gender = 1 if nxt.lemma.gender == 3 else nxt.lemma.gender
            return gender, nxt.lemma.plural_only or nxt.tag in (F.NOMINAL["pl"], F.NOMINAL["mpl"], F.NOMINAL["fpl"])
    gender = 2 if tok.tag in (F.NOMINAL["f"], F.NOMINAL["fpl"]) or lemma.gender == 2 else 1
    return gender, lemma.plural_only or tok.tag in (F.NOMINAL["pl"], F.NOMINAL["mpl"], F.NOMINAL["fpl"])


def _bare_nonfinite(other, tag: int, with_se: bool) -> str | None:
    """Another verb's infinitive or gerund, bare like the target (me voy a [quedar]: bañar)."""
    if other.verb is None:
        return None
    reflexive = other.verb.reflexive
    if tag == F.NONFINITE["inf"]:
        return other.es if with_se or not reflexive else other.es[:-2]
    gerunds = [f for f, t in other.forms if t == F.NONFINITE["ger"]]
    if with_se:
        return gerunds[0] if gerunds else None
    plain = [g for g in gerunds if not g.endswith("se")]
    return plain[0] if plain else None


def _candidates(b) -> None:
    from .build import _bare  # noqa: PLC0415

    d = b.diag
    _POOLS.clear()
    _GROUPS.clear()
    _POSITIONS.clear()
    first = _first_lessons(b)
    for item in b.items:
        def met(other, lesson=item.lesson) -> bool:
            return lesson == NONE16 or first.get(other.id, NONE16) <= lesson

        cands: list = []
        must = 0
        if item.kind in (VOCAB_RECOGNISE, VOCAB_PRODUCE):
            lemma = b.lemmas[item.a]
            produce = item.kind == VOCAB_PRODUCE
            partners = _confusable_partners(b, lemma)
            pool = [(o, o.es if produce else o.en) for o in _vocab_pool(b, lemma, produce, item.uid)]
            chosen = _select(pool, met, partners)
            must = min(3, sum(1 for o, _t in chosen if o in partners))
            cands = [o.id for o, _t in chosen]
        elif item.kind == CONJUGATION:
            lemma = b.lemmas[item.a]
            answer = lemma.verb.forms.get(F.verb_tag_parts(item.b), "")
            if not answer:
                d.error(item.where, "verb", f"{lemma.key} has no form {F.tag_name(item.b)}")
            cands = [c for c in _verb_candidates(lemma, item.b, answer, bare=False,
                                                 tenses=_taught_tenses(b, item.lesson))
                     if len(c) <= OPTION_MAX][:MAX_CANDIDATES]
        elif item.kind == CLOZE:
            sent = b.sentences[item.a]
            tok = sent.tokens[item.b]
            lemma = tok.lemma
            seen = {tok.surface.lower()}

            def push(text: str) -> bool:
                text = _gap_text(text, tok.surface)
                if text.lower() in seen or len(text) > OPTION_MAX:
                    return False
                seen.add(text.lower())
                cands.append(text)
                return True

            if lemma.verb is not None and F.is_verb_tag(tok.tag):
                for partner in _confusable_partners(b, lemma):
                    form = partner.verb.forms.get(F.verb_tag_parts(tok.tag)) if partner.verb else partner.es
                    if form and push(_bare(form)):
                        must += 1
                for form in _verb_candidates(lemma, tok.tag, tok.surface, bare=True,
                                             skip_forms=_you_conflicts(sent, item.b, tok),
                                             tenses=_taught_tenses(b, item.lesson)):
                    push(form)
                # The verb's own forms in the taught tenses are a closed set: early "you"
                # sentences may leave only two (¿[Habla] inglés? → hablo, hablamos).
                item.closed = True
            else:
                prev = sent.tokens[item.b - 1] if item.b > 0 else None
                adjacent = prev is not None and sent.es[prev.end:tok.start] == " "
                after_el = adjacent and prev.surface.lower() in EL_ARTICLES
                after_la = adjacent and prev.surface.lower() in LA_ARTICLES
                singular = tok.tag not in (F.NOMINAL["pl"], F.NOMINAL["mpl"], F.NOMINAL["fpl"]) and \
                    not lemma.plural_only
                el_context = lemma.pos == POS["noun"] and singular and (after_el or bool(lemma.flags & 4))
                tag = _agreement_tag(sent, item.b, tok) if lemma.pos == POS["adj"] else tok.tag
                if lemma.pos == POS["noun"] and lemma.gender == 3 and adjacent and prev.lemma is not None \
                        and prev.lemma.pos == POS["det"]:
                    # la [policía], una [estudiante]: options must fit the article.
                    feminine = prev.lemma.gender == 2 or prev.tag in (F.NOMINAL["f"], F.NOMINAL["fpl"])
                    plural = tok.tag in (F.NOMINAL["pl"], F.NOMINAL["mpl"], F.NOMINAL["fpl"])
                    if feminine:
                        tag = F.NOMINAL["fpl" if plural else "f"]
                partners = _confusable_partners(b, lemma)
                taken = []
                for partner in partners:
                    # An authored partner is always offered (that is what the set is for): in the
                    # agreeing form if it has one, else as written (papa against papá).
                    same_group = POS_GROUP.get(partner.pos) == POS_GROUP.get(lemma.pos)
                    form = _option_for(lemma, tag, partner, el_context, after_la) if same_group else None
                    form = form or partner.form_for(tok.tag) or partner.es
                    if form and push(form):
                        must += 1
                        taken.append((partner, cands[-1]))
                function_word = lemma.pos in (POS["det"], POS["pron"], POS["prep"], POS["conj"])
                nonfinite = lemma.verb is not None and tok.tag in (F.NONFINITE["inf"], F.NONFINITE["ger"])
                if function_word:
                    gender, plural = _det_agreement(sent, item.b, tok)
                options = []
                for other in _vocab_pool(b, lemma, produce=True, uid=item.uid):
                    if other in partners:
                        continue
                    if function_word:
                        # A closed class: possessives against possessives, este against ese and
                        # aquel, even if that leaves only one or two (pack-format.md 3.9).
                        form = _function_option(lemma, tok.tag, other, gender, plural)
                    elif nonfinite:
                        form = _bare_nonfinite(other, tok.tag, tok.surface.lower().endswith("se"))
                    else:
                        form = _option_for(lemma, tag, other, el_context, after_la)
                    if form:
                        options.append((other, _gap_text(form, tok.surface)))
                # este offers both ese and aquel, though they share "that"; the target's own
                # sense still keeps ese and aquel from being offered for each other.
                demonstrative = function_word and function_kind(lemma)[1] == "demonstrative"
                for other, text in _select(options, met, partners, taken, unrelated=not demonstrative)[len(taken):]:
                    push(text)
                item.closed = function_word
            cands = cands[:MAX_CANDIDATES]
            must = min(must, 3)
        elif item.kind == PHRASE:
            entry = b.phrase_entries[item.b]
            mine = b.sentences[entry.sentence]
            same = [e for e in b.phrase_entries if e.category == entry.category and e is not entry]
            other = [e for e in b.phrase_entries if e.category != entry.category]
            shown = {mine.en.lower(), mine.es.lower()}
            for e in same + other:
                s = b.sentences[e.sentence]
                if s.en.lower() not in shown and s.es.lower() not in shown:
                    shown |= {s.en.lower(), s.es.lower()}  # options pairwise distinct too
                    cands.append(e.sentence)
                if len(cands) >= MAX_CANDIDATES:
                    break
        item.candidates = cands
        item.must_show = must
        minimum = 1 if item.closed else 3
        if item.kind in (VOCAB_RECOGNISE, VOCAB_PRODUCE, CLOZE, CONJUGATION, PHRASE) and len(cands) < minimum:
            d.error(item.where, "distractors",
                    f"item '{item.key}' has {len(cands)} distractor(s); multiple choice needs {minimum} "
                    "(add lemmas of the same part of speech and level, or a confusables entry)")
