#pragma once

#include <builtinFonts/times_8_bold.h>
#include <builtinFonts/times_8_bolditalic.h>
#include <builtinFonts/times_8_italic.h>
#include <builtinFonts/times_8_regular.h>
#include <builtinFonts/times_9_bold.h>
#include <builtinFonts/times_9_bolditalic.h>
#include <builtinFonts/times_9_italic.h>
#include <builtinFonts/times_9_regular.h>
#include <builtinFonts/times_12_bold.h>
#include <builtinFonts/times_12_bolditalic.h>
#include <builtinFonts/times_12_italic.h>
#include <builtinFonts/times_12_regular.h>
#include <builtinFonts/times_14_bold.h>
#include <builtinFonts/times_14_bolditalic.h>
#include <builtinFonts/times_14_italic.h>
#include <builtinFonts/times_14_regular.h>
#include <builtinFonts/times_16_bold.h>
#include <builtinFonts/times_16_bolditalic.h>
#include <builtinFonts/times_16_italic.h>
#include <builtinFonts/times_16_regular.h>
#include <builtinFonts/helvetica_8_bold.h>
#include <builtinFonts/helvetica_8_bolditalic.h>
#include <builtinFonts/helvetica_8_italic.h>
#include <builtinFonts/helvetica_8_regular.h>
#include <builtinFonts/helvetica_9_bold.h>
#include <builtinFonts/helvetica_9_bolditalic.h>
#include <builtinFonts/helvetica_9_italic.h>
#include <builtinFonts/helvetica_9_regular.h>
#include <builtinFonts/helvetica_12_bold.h>
#include <builtinFonts/helvetica_12_bolditalic.h>
#include <builtinFonts/helvetica_12_italic.h>
#include <builtinFonts/helvetica_12_regular.h>
#include <builtinFonts/helvetica_14_bold.h>
#include <builtinFonts/helvetica_14_bolditalic.h>
#include <builtinFonts/helvetica_14_italic.h>
#include <builtinFonts/helvetica_14_regular.h>
#include <builtinFonts/helvetica_16_bold.h>
#include <builtinFonts/helvetica_16_bolditalic.h>
#include <builtinFonts/helvetica_16_italic.h>
#include <builtinFonts/helvetica_16_regular.h>
#include <builtinFonts/helveticaui_8_regular.h>
#include <builtinFonts/helveticaui_9_bold.h>
#include <builtinFonts/helveticaui_9_regular.h>
#include <builtinFonts/helveticaui_12_bold.h>
#include <builtinFonts/helveticaui_12_regular.h>
