// Generated by tools/gen-fsrs-vectors.py from py-fsrs 6.3.2. Do not edit.
#pragma once

namespace tinta::core {

inline constexpr char kFsrsVersion[] = "py-fsrs 6.3.2";
inline constexpr int kFsrsWeightCount = 21;
inline constexpr float kFsrsDefaultWeights[kFsrsWeightCount] = {
    0.212f,  1.2931f, 2.3065f, 8.2956f, 6.4133f, 0.8334f, 3.0194f, 0.001f,  1.8722f, 0.1666f, 0.796f,
    1.4835f, 0.0614f, 0.2629f, 1.6483f, 0.6014f, 1.8729f, 0.5425f, 0.0912f, 0.0658f, 0.1542f,
};

}  // namespace tinta::core
