#!/usr/bin/env python3
"""Generate canonical normalization data with pinned Unicode 15.1 properties."""
import argparse
from pathlib import Path
import unicodedata as unicode

VERSION = "15.1.0"


def generate():
    if unicode.unidata_version != VERSION:
        raise RuntimeError(f"Unicode {VERSION} required; found {unicode.unidata_version}")
    decompositions, scalars, classes, compositions = [], [], [], []
    for scalar in range(0x110000):
        if 0xAC00 <= scalar < 0xD7A4:
            continue
        char = chr(scalar)
        combining = unicode.combining(char)
        if combining:
            classes.append((scalar, combining))
        mapping = unicode.decomposition(char)
        if not mapping or mapping.startswith("<"):
            continue
        expanded = [ord(value) for value in unicode.normalize("NFD", char)]
        assert len(expanded) <= 4
        decompositions.append((scalar, len(scalars), len(expanded)))
        scalars.extend(expanded)
        pair = [int(value, 16) for value in mapping.split()]
        if len(pair) == 2 and unicode.normalize("NFC", "".join(map(chr, pair))) == char:
            compositions.append(((pair[0] << 21) | pair[1], scalar))
    compositions.sort()
    assert len({key for key, _ in compositions}) == len(compositions)
    # Place longer sequences first so singleton/subsequence mappings reuse them.
    sequences = {tuple(scalars[offset:offset + count]) for _, offset, count in decompositions}
    pool = []
    offsets = {}
    for sequence in sorted(sequences, key=lambda value: (-len(value), value)):
        offset = next((at for at in range(len(pool) - len(sequence) + 1)
                       if tuple(pool[at:at + len(sequence)]) == sequence), None)
        if offset is None:
            overlap = next((count for count in range(min(len(pool), len(sequence)), 0, -1)
                            if tuple(pool[-count:]) == sequence[:count]), 0)
            offset = len(pool) - overlap
            pool.extend(sequence[overlap:])
        offsets[sequence] = offset
    assert len(pool) < 4096 and max(pool) < (1 << 18)
    packed = bytearray((len(pool) * 18 + 7) // 8)
    for at, scalar in enumerate(pool):
        bit = at * 18
        value = scalar << (bit % 8)
        for byte in range(3):
            if bit // 8 + byte < len(packed):
                packed[bit // 8 + byte] |= (value >> (byte * 8)) & 255
    lines = ["// Generated by scripts/gen_companion_unicode.py; Unicode 15.1.0.",
             "// Canonical data only. Hangul syllables use algorithmic normalization.",
             "#pragma once", "#include <cstdint>", "namespace companion::unicode_data {",
             'inline constexpr char VERSION[] = "15.1.0";',
             "struct Decomposition { uint32_t bits;",
             "constexpr uint32_t scalar() const { return bits & 0x3ffff; }",
             "constexpr uint16_t offset() const { return (bits >> 18) & 0xfff; }",
             "constexpr uint8_t count() const { return (bits >> 30) + 1; } };",
             "struct Combining { uint32_t bits;",
             "constexpr uint32_t scalar() const { return bits & 0x1fffff; }",
             "constexpr uint8_t value() const { return bits >> 21; } };",
             "struct Composition { uint32_t low, high;",
             "constexpr uint64_t pair() const { return low | (uint64_t(high & 0x3ff) << 32); }",
             "constexpr uint32_t scalar() const { return high >> 10; } };",
             "static_assert(sizeof(Decomposition) == 4 && sizeof(Combining) == 4 && sizeof(Composition) == 8);"]
    lines.append("inline constexpr uint8_t SCALARS[] = {")
    lines.extend("".join(f"0x{value:02x}," for value in packed[at:at + 16]) for at in range(0, len(packed), 16))
    lines.extend(["};", "inline constexpr uint32_t scalarAt(uint16_t at) {",
                  "const uint32_t bit = uint32_t(at) * 18; const uint32_t byte = bit / 8;",
                  "return ((uint32_t(SCALARS[byte]) | (uint32_t(SCALARS[byte + 1]) << 8) |",
                  "(uint32_t(SCALARS[byte + 2]) << 16)) >> (bit % 8)) & 0x3ffff;", "}"])
    lines.append("inline constexpr Decomposition DECOMPOSITIONS[] = {")
    for scalar, offset, count in decompositions:
        assert scalar < (1 << 18) and 1 <= count <= 4
        position = offsets[tuple(scalars[offset:offset + count])]
        lines.append(f"{{0x{scalar | (position << 18) | ((count - 1) << 30):x}}},")
    lines.append("};\ninline constexpr Combining CLASSES[] = {")
    lines.extend(f"{{0x{scalar | (value << 21):x}}}," for scalar, value in classes)
    lines.append("};\ninline constexpr Composition COMPOSITIONS[] = {")
    for pair, scalar in compositions:
        assert pair < (1 << 42) and scalar < (1 << 21)
        bits = pair | (scalar << 42)
        lines.append(f"{{0x{bits & 0xffffffff:x},0x{bits >> 32:x}}},")
    lines.append("};\n} // namespace companion::unicode_data")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate()
    if args.check:
        if args.output.read_text() != text:
            raise SystemExit("Normalization data differs; regenerate with pinned Unicode 15.1.0")
    else:
        args.output.write_text(text)


if __name__ == "__main__":
    main()
