#!/usr/bin/env python3
"""Generate built-in font headers sharing byte-identical compressed groups."""
from collections import Counter
from pathlib import Path
import re

BITMAP = re.compile(r'static const uint8_t (\w+)Bitmaps\[(\d+)\] = \{(.*?)\n\};', re.S)
GROUPS = re.compile(r'static const EpdFontGroup (\w+)Groups\[\] = \{(.*?)\n\};', re.S)
ROW = re.compile(r'\{\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+)\s*\}')


def read_font(path):
    text = path.read_text()
    bitmap, groups = BITMAP.search(text), GROUPS.search(text)
    if not bitmap or not groups or bitmap[1] != groups[1]:
        raise ValueError(f'{path}: expected compressed built-in font')
    data = bytes(int(x, 16) for x in re.findall(r'0x([0-9a-fA-F]{2})', bitmap[3]))
    if len(data) != int(bitmap[2]):
        raise ValueError(f'{path}: bitmap extent mismatch')
    rows = [tuple(map(int, row)) for row in ROW.findall(groups[2])]
    covered = 0
    for offset, size, _, _, _ in rows:
        if offset != covered or not size or offset + size > len(data):
            raise ValueError(f'{path}: incomplete or overlapping groups')
        covered += size
    if not rows or covered != len(data):
        raise ValueError(f'{path}: incomplete group coverage')
    return text, bitmap, groups, data, rows


def byte_array(name, data):
    rows = [', '.join(f'0x{x:02x}' for x in data[i:i + 16]) for i in range(0, len(data), 16)]
    return f'static constexpr uint8_t {name}[{len(data)}] = {{\n' + ''.join(f'    {row},\n' for row in rows) + '};'


def write_changed(path, text):
    if not path.exists() or path.read_text() != text:
        path.write_text(text)


def generate(source, destination):
    source, destination = Path(source), Path(destination)
    paths = [path for path in sorted(source.glob('*.h')) if path.name != 'all.h']
    fonts = [(path, read_font(path)) for path in paths if GROUPS.search(path.read_text())]
    if not fonts:
        raise ValueError('No built-in fonts found')
    streams = Counter()
    for _, (_, _, _, data, rows) in fonts:
        for offset, size, _, _, _ in rows:
            streams[data[offset:offset + size]] += 1
    shared = {data: f'builtinSharedGroup{index}' for index, data in enumerate(streams) if streams[data] > 1}
    destination.mkdir(parents=True, exist_ok=True)
    preamble = '// Generated by share_builtin_font_groups.py; do not edit.\n#pragma once\n'
    write_changed(destination / 'shared.generated.h', preamble + '#include <cstdint>\n\n' +
                  '\n\n'.join(byte_array(name, data) for data, name in shared.items()) + '\n')
    original_bytes = local_bytes = metadata_pointers = 0
    for path, (text, bitmap, groups, data, rows) in fonts:
        local, changed_rows = bytearray(), []
        original_bytes += len(data)
        for offset, size, unpacked, count, first in rows:
            stream = data[offset:offset + size]
            if stream in shared:
                new_offset, pointer = 0, shared[stream]
            else:
                new_offset, pointer = len(local), 'nullptr'
                local.extend(stream)
            changed_rows.append(f'    {{ {new_offset}, {size}, {unpacked}, {count}, {first}, {pointer} }},')
            metadata_pointers += 1
        if not local:
            raise ValueError(f'{path}: no local bitmap data')
        local_bytes += len(local)
        replacement = f'static const EpdFontGroup {groups[1]}Groups[] = {{\n' + '\n'.join(changed_rows) + '\n};'
        text = text[:groups.start()] + replacement + text[groups.end():]
        text = text[:bitmap.start()] + byte_array(bitmap[1] + 'Bitmaps', local) + text[bitmap.end():]
        text = preamble + '#include "shared.generated.h"\n' + text
        write_changed(destination / (path.stem + '.generated.h'), text)
    write_changed(destination / 'all.generated.h', preamble + ''.join(
        (f'#include "{path.stem}.generated.h"\n' if GROUPS.search(path.read_text())
         else f'#include "../{path.name}"\n') for path in paths))
    unique_bytes = sum(len(data) for data in shared)
    result = dict(original=original_bytes, shared=unique_bytes, local=local_bytes,
                  saved_stream_bytes=original_bytes - local_bytes - unique_bytes,
                  group_count=metadata_pointers, font_count=len(fonts))
    return result


if __name__ == '__main__':
    root = Path(__file__).resolve().parents[1]
    source = root / 'lib/EpdFont/builtinFonts'
    print('Shared built-in font groups:', generate(source, source / 'deduplicated'))
else:
    try:
        Import('env')  # noqa: F821 - PlatformIO/SCons
    except NameError:
        pass
    else:
        source = Path(env['PROJECT_DIR']) / 'lib/EpdFont/builtinFonts'
        print('Shared built-in font groups:', generate(source, source / 'deduplicated'))
