// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define TIMES_8_FONT_ID (-2009346977)
#define TIMES_9_FONT_ID (1379946794)
#define TIMES_12_FONT_ID (1180753889)
#define TIMES_14_FONT_ID (876142804)
#define TIMES_16_FONT_ID (-1793930043)
#define HELVETICA_8_FONT_ID (1335070343)
#define HELVETICA_9_FONT_ID (409265535)
#define HELVETICA_12_FONT_ID (-1512941805)
#define HELVETICA_14_FONT_ID (-1965377881)
#define HELVETICA_16_FONT_ID (-1289126699)
#define UI_10_FONT_ID (1730554756)
#define UI_12_FONT_ID (333149352)
#define SMALL_FONT_ID (501618249)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(TIMES_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TIMES_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TIMES_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TIMES_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TIMES_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
