// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define TIMES_8_FONT_ID (-815620062)
#define TIMES_9_FONT_ID (1352044738)
#define TIMES_12_FONT_ID (1699775548)
#define TIMES_14_FONT_ID (-3497711)
#define TIMES_16_FONT_ID (-1608167556)
#define HELVETICA_8_FONT_ID (-971985407)
#define HELVETICA_9_FONT_ID (1952467069)
#define HELVETICA_12_FONT_ID (-1027724045)
#define HELVETICA_14_FONT_ID (-1965377881)
#define HELVETICA_16_FONT_ID (-1644108173)
#define UI_10_FONT_ID (62651974)
#define UI_12_FONT_ID (-1150839306)
#define SMALL_FONT_ID (-1682977342)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(TIMES_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TIMES_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TIMES_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TIMES_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TIMES_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
