// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define TIMES_8_FONT_ID (143375046)
#define TIMES_9_FONT_ID (-351736808)
#define TIMES_12_FONT_ID (317824101)
#define TIMES_14_FONT_ID (1780663208)
#define TIMES_16_FONT_ID (2101936137)
#define HELVETICA_8_FONT_ID (195523349)
#define HELVETICA_9_FONT_ID (-1679424824)
#define HELVETICA_12_FONT_ID (-1933879008)
#define HELVETICA_14_FONT_ID (435898238)
#define HELVETICA_16_FONT_ID (-1051315077)
#define UI_10_FONT_ID (-1735774813)
#define UI_12_FONT_ID (780768993)
#define SMALL_FONT_ID (-221426880)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(TIMES_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TIMES_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TIMES_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TIMES_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(TIMES_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_9_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HELVETICA_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
