#pragma once

// AUTO-GENERATED by tools/bdf2freeink.py from tools/fonts.manifest — do not edit
// by hand. One BitmapFont per strike, each defined in its own .cpp here.

#include <FreeInkUIFont.h>

namespace tinta::fonts {

extern const freeink::ui::BitmapFont kTimesRoman22;  // Times Roman 22 px, timR16.bdf
extern const freeink::ui::BitmapFont kTimesRoman25;  // Times Roman 25 px, timR18.bdf
extern const freeink::ui::BitmapFont kTimesRoman29;  // Times Roman 29 px, timR21.bdf
extern const freeink::ui::BitmapFont kTimesBold22;  // Times Bold 22 px, timB16.bdf
extern const freeink::ui::BitmapFont kTimesBold25;  // Times Bold 25 px, timB18.bdf
extern const freeink::ui::BitmapFont kTimesBold29;  // Times Bold 29 px, timB21.bdf
extern const freeink::ui::BitmapFont kTimesItalic22;  // Times Italic 22 px, timI16.bdf
extern const freeink::ui::BitmapFont kTimesItalic25;  // Times Italic 25 px, timI18.bdf
extern const freeink::ui::BitmapFont kTimesItalic29;  // Times Italic 29 px, timI21.bdf
extern const freeink::ui::BitmapFont kTimesBold34;  // Times Bold 34 px, timB24.bdf
extern const freeink::ui::BitmapFont kTermesBold50;  // TeX Gyre Termes Bold 50 px (FreeType, hinted), outline/texgyretermes-bold.otf
extern const freeink::ui::BitmapFont kTermesBold58;  // TeX Gyre Termes Bold 58 px (FreeType, hinted), outline/texgyretermes-bold.otf
extern const freeink::ui::BitmapFont kTermesBold68;  // TeX Gyre Termes Bold 68 px (FreeType, hinted), outline/texgyretermes-bold.otf
extern const freeink::ui::BitmapFont kTermesBold75;  // TeX Gyre Termes Bold 75 px (FreeType, hinted), outline/texgyretermes-bold.otf
extern const freeink::ui::BitmapFont kTermesBold87;  // TeX Gyre Termes Bold 87 px (FreeType, hinted), outline/texgyretermes-bold.otf
extern const freeink::ui::BitmapFont kHelvetica17;  // Helvetica 17 px, helvR12.bdf
extern const freeink::ui::BitmapFont kHelvetica20;  // Helvetica 20 px, helvR14.bdf
extern const freeink::ui::BitmapFont kHelvetica22;  // Helvetica 22 px, helvR16.bdf
extern const freeink::ui::BitmapFont kHelvetica25;  // Helvetica 25 px, helvR18.bdf
extern const freeink::ui::BitmapFont kHelvetica29;  // Helvetica 29 px, helvR21.bdf
extern const freeink::ui::BitmapFont kHelvetica34;  // Helvetica 34 px, helvR24.bdf
extern const freeink::ui::BitmapFont kHelveticaOblique17;  // Helvetica Oblique 17 px, helvO12.bdf
extern const freeink::ui::BitmapFont kHelveticaOblique20;  // Helvetica Oblique 20 px, helvO14.bdf
extern const freeink::ui::BitmapFont kHelveticaOblique22;  // Helvetica Oblique 22 px, helvO16.bdf
extern const freeink::ui::BitmapFont kHelveticaBold14;  // Helvetica Bold 14 px, helvB10.bdf
extern const freeink::ui::BitmapFont kHelveticaBold17;  // Helvetica Bold 17 px, helvB12.bdf
extern const freeink::ui::BitmapFont kHelveticaBold20;  // Helvetica Bold 20 px, helvB14.bdf
extern const freeink::ui::BitmapFont kHelveticaBold25;  // Helvetica Bold 25 px, helvB18.bdf

}  // namespace tinta::fonts
